---
title: "Combined Graphic"
format: html
editor: visual
---


```{r}
library(colorspace)
library(geofacet) 
library(ggtext) 
library(glue) 
library(grid)
library(magick)
library(patchwork) 
library(scales) 
library(showtext) 
library(tidyverse) 
library(dplyr)
library(forcats)
```

```{r}
#......................import Google fonts.......................
sysfonts::font_add_google(name = "Orbitron", family = "orb")
sysfonts::font_add_google(name = "Barlow", family = "bar")

#....................import FontAwesome fonts....................
sysfonts::font_add(family = "fa-brands", regular = here::here("fonts", "Font Awesome 6 Brands-Regular-400.otf"))
sysfonts::font_add(family = "fa-solid", regular = here::here("fonts", "Font Awesome 6 Free-Solid-900.otf"))
```


```{r}
bg <- "#E8ECF0" 
```


```{r}
plot_base <- ggplot() +
  
# create a title and subtitle
  labs(
    title = "PM 2.5",
    subtitle = "TBD",
    caption = "tbd" # predefined in previous code chunk
    ) +
  
# apply a completely empty theme ----
  theme_void() +
  
# further customize theme ----
  theme(
    
# # customize overall text 
#     text = element_text(family = "Arial", 
#                         size = 48, 
#                         lineheight = 0.3, # vertical spacing between lines
#                         color = "red"),
    
# make the background grey
    plot.background = element_rect(fill = bg, 
                                   color = bg),
    
# customize the title
    plot.title = element_text(size = 50, 
                              face = "bold", 
                              hjust = 0.5, # center alignment
                              margin = margin(b = 10)), # margin (space) below text
    
# customize the subtitle
    plot.subtitle = element_text(family = "Arial", 
                                 hjust = 0.5, 
                                 margin = margin(b = 20)), # margin (space) below subtitle
#     
# # format plot caption using {ggtext} to render fontawesome icons ----
#     plot.caption = ggtext::element_markdown(family = "Arial",
#                                             face = "italic",
#                                             color = colorspace::darken("red", 0.25),
#                                             # slightly darker color for accent
#                                             hjust = 0.5, 
#                                             margin = margin(t = 20)),

# add specific margins for spacing around infographic
    plot.margin = margin(b = 20, # botton
                         t = 50, # top
                         r = 50, # right
                         l = 50) # left
    
  )

plot_base
# ggsave("outputs/plot_base.png", plot_base, width = 5, height = 5)
```


```{r}
plot_final <- plot_base +
  inset_element(pm_map, left = 0.5, right = 1, top = 1, bottom = 0.4) +  # Map higher on right
  inset_element(aqi_plot, left = 0, right = 0.45, top = 0.6, bottom = 0.2) +  # AQI lower on left
  inset_element(main_pollutant_circles, left = 0.2, right = 0.5, top = 1, bottom = 0.65) +  # Circles top center
  plot_annotation(
    theme = theme(
      plot.background = element_rect(fill = bg, color = bg)
    )
  )

ggsave(plot = plot_final, 
       filename = here::here("output/PM_infographic.png"), 
       height = 16, 
       width = 10)
plot_final
```
