---
title: "HW3-drafting-viz"
format: html
editor: visual
---

1.  Which option do you plan to pursue? It’s okay if this has changed since HW #1.

    I'm still planning on pursuing the infographic.

2.  Restate your question(s). Has this changed at all since HW #1? If yes, how so?

    My questions have shifted slightly since Homework 1 -

    -   How have major air pollutants trended over the last 10–20 years in Los Angeles, CA?

    -   Which pollutants are the biggest contributors to poor AQI?

        -   **It's PM 2.5**

    -   Which areas of Los Angeles are most affected by PM2.5?

        -   what are the impacts on residents?

    -   What are the sources of PM2.5?

3.  Explain which variables from your data set(s) you will use to answer your question(s), and how.

    -   To see how air pollution as trended over time, I've used AQI Summary data from the EPA. I was able to calculate the median AQI per year from 2000-2024, giving me two variables, AQI (number) and year (number). Using the same AQI data, I was able to see the main pollutants contributing to the AQI by grouping by year and pollutant to see the top pollutants per year. I was then able to average those counts to get the top pollutant count for 2000-2024, giving me two variables, main pollutant (chr) and average count (number).

    -   To see which areas are most affected by PM 2.5 in Los Angeles, I used CalEnviroscreen data. After tidying the spatial data to show only the incorporated regions of Los Angeles County, I was able to plot PM 2.5 percentile across the county. The variables I've filtered and selected for in the Enviroscreen data include PM 2.5 percentile (num), tract (num), zip (num), geometry (sfc). I kept zip code for quick area reference.

    -   To see the sources of PM 2.5, I tidied and wrangled two datasets, Point Sources and Nonpoint Sources, from the EPA's National Emissions Inventory (NEI) for the most recent year available (2020). After joining the datasets, I was left with three variables: pollution source (chr), source type (chr), and total emissions (num).

4.  In [HW #2](https://eds-240-data-viz.github.io/course-materials/assignments/HW2.html), you created some exploratory data viz to better understand your data. You may already have some ideas of how you plan to formally visualize your data, but it’s *incredibly* helpful to look at visualizations by other creators for inspiration. Find *at least two* data visualizations that you could (potentially) borrow / adapt pieces from. Link to them or download and embed them into your `.qmd` file, and explain which elements you might borrow (e.g. the graphic form, legend design, layout, etc.).

[Cédric Scherer - donut](https://www.cedricscherer.com/top/dataviz/#variousclients)

<https://www.studioterp.nl/charted-popular-science-a-datavisualization-by-studio-terp/>

[Nicola Rennie](https://github.com/nrennie)

<https://www.instagram.com/p/CAszZuIBxQQ/?hl=en>

<https://eds-240-data-viz.github.io/course-materials/lecture-slides/lecture5.1-good-viz-slides.html#/dual-axes-alt-prioritize>

5.  Hand-draw your anticipated visualizations, then take a photo of your drawing(s) and embed it in your rendered `.qmd` file – **note** that these are not *exploratory* visualizations, but rather your plan for your final visualizations that you will eventually polish and submit with HW #4. You should have:

```         
-   a sketch of your infographic (which should include at least three component visualizations) if you are pursuing [option 1](https://eds-240-data-viz.github.io/course-materials/assignments/HW4.html#option-1)
```

6.  Mock up **all** of your hand drawn visualizations using code. We understand that you will continue to iterate on these into HW #4 (particularly after receiving feedback), but by the end of HW #3, you should:

    -   have your data plotted (if you’re experimenting with a graphic form(s) that was not explicitly covered in class, we understand that this may take some more time to build; you should have as much put together as possible)

    -   use appropriate strategies to highlight / focus attention on a clear message

    -   include appropriate text such as titles, captions, axis labels

    -   experiment with colors and typefaces / fonts

    -   create a presentable / aesthetically-pleasing theme (e.g. (re)move gridlines / legends as appropriate, adjust font sizes, etc.)

7.  Answer the following questions:

    -   **a.** What challenges did you encounter or anticipate encountering as you continue to build / iterate on your visualizations in R? If you struggled with mocking up any of your three visualizations (from #6, above), describe those challenges here.

    -   **b.** What ggplot extension tools / packages do you need to use to build your visualizations? Are there any that we haven’t covered in class that you’ll be learning how to use for your visualizations?

    -   **c.** What feedback do you need from the instructional team and / or your peers to ensure that your intended message is clear?
